config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace="catalog")),
    path('users/', include('users.urls', namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, password_recovery

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_recovery/', password_recovery, name='password_recovery'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="email")

    avatar = models.ImageField(
        upload_to="users/avatar/", verbose_name="аватар", **NULLABLE
    )
    phone = models.CharField(max_length=20, verbose_name="телефон", **NULLABLE)
    country = models.CharField(max_length=50, verbose_name="страна", **NULLABLE)
    token = models.CharField(max_length=100, verbose_name="token", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        # Строковое отображение объекта
        return f"{self.email}"

    class Meta:
        verbose_name = "пользователь"  # Настройка для наименования одного объекта
        verbose_name_plural = (
            "пользователи"  # Настройка для наименования набора объектов
        )

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm (StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2",)


class UserProfileForm (StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ("email", 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm
from users.func import make_random_password

from users.models import User


class RegisterView(CreateView):
    """
    Регистрация нового пользователя
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """
        Отправка пользователю ссылки для проверки подлинности данных
        """
        user = form.save()
        # print(user)
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        # print(url)
        send_mail(
            subject='подтверждение почты на нашем сайте',
            message=f'Привет!\n Прейдите по ссылке в подтверждение своей почты \n '
                    f'{url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    """
    Проверка подлинности ч/з ссылку
    """
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def password_recovery(request):
    """
    Восстановление пароля
    """
    if request.method == 'POST':
        email = request.POST.get('email')
        # print(f"есть {email}")      # проверка наличия адреса в БД

        if User.objects.filter(email=email):
            user = User.objects.get(email=email)
            # characters = string.ascii_letters + string.digits + string.punctuation
            # new_password = ''.join(secrets.choice(characters) for item in range(10))
            new_password = make_random_password()
            user.password = make_password(password=new_password, salt=None, hasher='default')
            # user.set_password(new_password)
            user.save()
            # print(user.password)
            send_mail(
                subject='Восстановление пароля',
                message=f'Привет! новый пароль для входа на сайт: \n'
                        f'{new_password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email]
            )
            return HttpResponseRedirect(reverse_lazy('users:login'))

        else:
            print('нет в БД')
            return HttpResponseRedirect(reverse_lazy('users:login'))

    return render(request, 'users/password_recovery.html')


class ProfileView(UpdateView):
    """
    Данные активного пользователя и возможность их изменения
    """
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('catalog:homepage')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-offset-12">
    <div class="card box-shadow">

        <form method="post" action="" class="form-floating text-center"
              enctype="multipart/form-data">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h2 class="my-0 font-weight-normal text-center">Авторизация</h2>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-6">
                                        <button type="submit" class="btn btn-lg  btn-outline-warning">
                                            Войти
                                        </button>
                                    </div>
                                     <div class="col-6 mb-2">
                                        <a class="p-2 btn btn-outline-warning btn-lg"
                                           href="{% url 'users:password_recovery' %}"
                                           role="button">Восстановить пароль</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_recovery.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-offset-12">
    <div class="card box-shadow">

        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <form method="POST" action="" class="form-floating text-center"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-header">
                            <h2 class="my-0 font-weight-normal text-center mb-3">Восстановление пароля</h2>
                            <h5 class="my-0 font-weight-normal text-center text-secondary">Укажите свою электронную почту,</h5>
                            <h5 class="my-0 font-weight-normal text-center text-secondary mb-3">на которую направить Вам новый пароль</h5>
                        </div>
                        <div class="card-body">

                                <input type="email" class="form-control mb-4" name="email"
                                       placeholder="Введите Ваш email, зарегистрированный на сайте"/>

                        </div>
                            <div class="card-footer">
                                <input type="submit" value="Отправить" class="btn btn-lg  btn-outline-warning mt-4"/>
                            </div>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-offset-12 text-center">
    <div class="card box-shadow ">

        <form method="post" action="" class="form-floating text-center"
              enctype="multipart/form-data">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                    <div class="card">
                        <div class="card-header">
                            {% if object.is_active %}
                            <h2 class="my-0 font-weight-normal text-center">Редактирование профиля</h2>
                             {% else %}
                             <h2 class="my-0 font-weight-normal text-center">Регистрация</h2>
                             {% endif %}
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-6 text-center mb-2">
                                        {% if object.is_active %}
                                        <button type="submit" class="btn btn-lg  btn-outline-warning">
                                            Сохранить изменения
                                        </button>
                                        {% else %}
                                        <button type="submit" class="btn btn-lg  btn-outline-warning">
                                            Зарегистрироваться
                                        </button>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>
{% endblock %}