catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import (ProductListView, ProductCreateView, UserContactsCreateView,
                           ProductDetailView, MyContactListView, BlogListView, BlogCreateView,
                           BlogUpdateView, BlogDeleteView, BlogDetailView, ProductUpdateView, CategoryListView)

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='homepage'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='view_product'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('create/', never_cache(ProductCreateView.as_view()), name='product_create'),

    path('category', CategoryListView.as_view(), name='category'),

    path('blog', BlogListView.as_view(), name='blog'),
    path('blog/create/', never_cache(BlogCreateView.as_view()), name='blog_create'),
    path('blog/update/<slug:slug>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/view/<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),

    path('usercontacts/', UserContactsCreateView.as_view(), name='user_contacts'),
    path('mycontact/', MyContactListView.as_view(), name='my_contact'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace="catalog")),
    path('users/', include('users.urls', namespace="users")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, password_recovery

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_recovery/', password_recovery, name='password_recovery'),
]

catalog/forms.py
from django.core.exceptions import ValidationError

from django import forms
from django.forms import BooleanField, BaseInlineFormSet

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = "form-check-input"
            else:
                field.widget.attrs['class'] = "form-control"


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("created_at", "updated_at", "owner")

    def clean_product_name(self):
        cleaned_data = self.cleaned_data.get('product_name')
        words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')
        for word in words:
            if word in cleaned_data:
                raise ValidationError(f"Слово {word} не может содержаться в названии")
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        words = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')
        for word in words:
            if word in cleaned_data:
                raise ValidationError(f"Слово {word} не может содержаться в описании")
        return cleaned_data


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ("is_published", "description", "category")


class VersionForm(StyleFormMixin, forms.ModelForm):
    """ VersionForm"""

    class Meta:
        model = Version
        fields = "__all__"


class VersionFormSet(BaseInlineFormSet):
    """ Проверка между формами"""
    def clean(self):
        super().clean()
        active_versions = [form.cleaned_data for form in self.forms
                           if form.cleaned_data.get('is_active')]
                           # and not form.cleaned_data.get('DELETE', False)]
        if len(active_versions) > 1:
            raise ValidationError("Может быть только одна активная форма")

        return active_versions

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.forms import inlineformset_factory
# from django.shortcuts import render   # ДЗ 20.1
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from catalog.forms import ProductForm, VersionForm, VersionFormSet, ProductModeratorForm
# from catalog.management.commands.fill import Command   #ДЗ 20.1
from catalog.models import MyContact, Product, Category, UserContacts, Blog, Version
from catalog.services import get_category_from_cache
from config.settings import EMAIL_HOST_USER


class CategoryListView(ListView):
    model = Category
    extra_context = {'title': 'Страница категорий Вкусняшек'}

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     get_category_from_cache()
    #     return context_data

    def get_queryset(self):
        return get_category_from_cache()


class ProductListView(ListView):
    model = Product
    extra_context = {'title': 'Главная страница Вкусняшек'}
    paginate_by = 5
    orphans = 4

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = Category.objects.all()
        vers = Version.objects.filter(is_active=True)
        context_data['active_versions'] = vers
        user = self.request.user
        context_data['user'] = user
        # print(context_data)
        return context_data

    def get_queryset(self):
        return Product.objects.all().order_by('product_name')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:homepage')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm,
                                               extra=1)
        if self.request.method == 'POST':
            context_data["formset"] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            user = self.request.user
            self.object.owner = user
            self.object.save()
            # print(self.object)
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

#     # five_latest_products = Command.json_read_products()[-5:]  #ДЗ 20.1
#     # for prod in five_latest_products:
#     #     print(prod["fields"]["product_name"])


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    # form_class = ProductForm
    success_url = reverse_lazy('catalog:homepage')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, form=VersionForm,
                                               formset=VersionFormSet, extra=1)
        if self.request.method == 'POST':
            # print(f'1 ............. {context_data}, {self.request.method}')
            context_data["formset"] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = ProductFormset(instance=self.object)
            # print(context_data["formset"])
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        """Права доступа владельца, менеджера"""
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm("catalog.cancel_published_status")
                and user.has_perm("catalog.can_edit_description")
                and user.has_perm("catalog.can_edit_category")):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    extra_context = {
        'title': 'Вот что ты выбрал',
    }


class UserContactsCreateView(CreateView):
    model = UserContacts
    extra_context = {'title': 'Вкусняшка от пользователя'}
    fields = ('name', 'phone', 'email', 'message')
    success_url = reverse_lazy('catalog:homepage')
    print(UserContacts)


class MyContactListView(ListView):
    model = MyContact
    extra_context = {'title': 'Наши Контакты'}


class BlogListView(ListView):
    model = Blog
    extra_context = {'title': '???  Оказывается это интересно'}


class BlogCreateView(PermissionRequiredMixin, CreateView):
    model = Blog
    permission_required = 'catalog.add_blog'
    extra_context = {'title': 'Отлично! ты хочешь поделиться интересной статьей'}
    fields = ('title', 'preview', 'content', 'is_published')
    success_url = reverse_lazy('catalog:blog')

    def form_valid(self, form):
        if form.is_valid:
            new_nat = form.save()
            new_nat.slug = slugify(new_nat.title)
            new_nat.save()
            return super().form_valid(form)


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    permission_required = 'catalog.change_blog'
    extra_context = {'title': 'Что случилось? ты хочешь изменить?'}
    fields = ('title', 'preview', 'content', 'is_published')
    # success_url = reverse_lazy('catalog:blog')

    def form_valid(self, form):
        if form.is_valid:
            new_nat = form.save()
            new_nat.slug = slugify(new_nat.title)
            new_nat.save()
            return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:blog')


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    permission_required = 'catalog.delete_blog'
    extra_context = {'title': 'Всё  неправда и скучно'}
    success_url = reverse_lazy('catalog:blog')


class BlogDetailView(DetailView):
    model = Blog
    extra_context = {'title': 'Интересно...'}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        if self.object.views_count == 100:
            send_mail(
                "Поздравляю",
                f"Количество просмотров достигло 100, блог: '{self.object.title}'.",
                EMAIL_HOST_USER,
                ["knopisha.zh@gmail.com"],
                fail_silently=False,
            )
        return self.object

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

catalog/templates/catalog/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>yummy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="p-3 mb-2 bg-body-secondary">

    {% include 'catalog/includes/inc_main_menu.html' %}


    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Логотип сайта
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Список дел</a></li>
                    <li><a class="text-muted" href="#">Расписание гостей</a></li>
                    <li><a class="text-muted" href="#">Полезные советы</a></li>
                    <li><a class="text-muted" href="#">Меню</a></li>

                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Нас показывают</a></li>
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/mycontact/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-offset-12">
    <div class="card box-shadow">
        <div class="card-header">
            <h2 class="my-0 font-weight-normal text-center text-warning">Начнём ...</h2>
        </div>

        <div class="card-body">
            <form method="post" action="" class="form-floating text-center">
                {% csrf_token %}
                <p>Если Вам не нравиться блог "{{ object.title }}" - то прошу подтвердить его удаление</p>

                <button type="submit" class="btn btn-lg  btn-outline-warning">Да, подтвердить</button>
                <a class="btn btn-warning btn-lg mb-6"
                   href="{% url 'catalog:blog' %}"
                   role="button">Отменить удаление, вернуться в блог</a>

            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">{{ object.title}}</h2>
    <div class="row">
        <div class="col-8">
            <p class="lead">{{ object }}</p>
        </div>
        <div class="col-4">
            <div class="row">
                <h4 class="row text-warning">Количество просмотров: {{ object.views_count }}</h4>

                <img class="img-thumbnail" src="{{ object.preview|my_media }}">
            </div>

            <div class="d-grid gap-2">
                <div class="row">
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:blog_create' %}"
                       role="button">Можешь оставить свой блог у нас</a>
                </div>
                <div class="row">
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:blog' %}"
                       role="button">Блог для любознательных</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-offset-12">
    <div class="card box-shadow">
        <div class="card-header">
            <h2 class="my-0 font-weight-normal text-center text-warning">Начнём ...</h2>
        </div>

        <div class="card-body">
            <form method="post" action="" class="form-floating text-center"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="p-2 btn btn-lg  btn-outline-warning mb-2">Сохранить</button>
                <a class="p-2 btn btn-outline-warning btn-lg mb-2"
                   href="{% url 'catalog:blog' %}" role="button">Публиковать не хочу, отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Интересные статьи</h1>
    <p class="lead">Давайте посмотрим что тут мы написали, а может и Вы что-то напишете сами...</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-sm-12 col-lg-8 col-md-8">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal text-warning">Уже что-то есть...</h2>
                </div>
                <div class="mb-4"></div>
                <div class="card-body">

                    {% for object in object_list %}
                    {% if object.is_published %}

                    <div class="row text-align:left">
                        <div class="card-header"></div>
                        <div class="col-4">
                            <img class="img-thumbnail" src="{{ object.preview|my_media }}">
                        </div>
                        <div class="col-8">
                            <ol class="list-unstyled mt-3 mb-6 text-start m-3">
                                <li><h6> - {{ object|truncatechars:100 }}</h6></li>
                            </ol>
                            <div class="row">
                                <a class="p-2 btn btn-outline-warning mb-2"
                                   href="{% url 'catalog:view_blog' object.slug %}" role="button">Показать</a>
                                <a class="p-2 btn btn-outline-warning mb-2"
                                   href="{% url 'catalog:blog_update' object.slug %}" role="button">Изменить</a>
                                <a class="p-2 btn btn-outline-warning mb-2"
                                   href="{% url 'catalog:blog_delete' object.slug %}" role="button">Удалить</a>
                            </div>
                        </div>
                    </div>

                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-sm-10 col-lg-3 col-md-10 mx-auto">
            <div class="d-grid gap-2">
                <div class="row">
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:blog_create' %}"
                       role="button">Можешь оставить свой блог у нас</a>
                </div>
                <div class="row">
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:blog' %}"
                       role="button">Блог для любознательных</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Категории наших вкусняшек</h1>
    <p class="lead">Давайте посмотрим какие виды вкусняшек мы выбрали</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-sm-12 col-lg-8 col-md-8">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal text-warning">Для начала есть такие виды ...</h2>
                </div>

                <div class="row text-align:left">
                    <div class="card-body"></div>

                    {% for object in object_list %}
                    <ol class="list-unstyled mt-3 mb-6 text-start m-3">
                        <li><h6> - {{ object }}</h6></li>
                    </ol>
                    {% endfor %}
                </div>
            </div>
        </div>


    <div class="col-sm-10 col-lg-3 col-md-10 mx-auto">
        <div class="d-grid gap-2">
            <div class="row">
                <a class="btn btn-warning btn-lg mb-6"
                   href="{% url 'catalog:homepage' %}"
                   role="button">Вернуться на главную</a>
            </div>
            <div class="row">
                <a class="btn btn-warning btn-lg mb-6"
                   href="{% url 'catalog:blog' %}"
                   role="button">Блог для любознательных</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/mycontact_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4 text-warning">Информация о ... НАС</h2>
    <p class="lead">Здесь расскажем кто мы, где мы и как с нами можно связаться</p>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        {% for object in object_list %}
                        <tr>
                            <td class="w-50">Наименование</td>
                            <td>{{ object.contact_name }}</td>
                        </tr>
                        <tr>
                            <td class="w-50">Страна</td>
                            <td>{{ object.country }}</td>
                        </tr>
                        <tr>
                            <td class="w-50">ИНН</td>
                            <td>{{ object.inn }}</td>
                        </tr>
                        <tr>
                            <td class="w-50">Почтовый адрес</td>
                            <td>{{ object.address }}</td>
                        </tr>
                        <tr>
                            <td class="w-50">Адрес электронной почты</td>
                            <td>{{ object.email }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">{{ object.product_name}}</h2>
    <p class="lead">{{ object }}</p>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-8 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">

                <img class="card-img-top" src="{{ object.preview|my_media }}">
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-6 box-shadow">
                <div class="card-header">
                    {% if perms.catalog.cancel_published_status and perms.catalog.can_edit_description and perms.catalog.can_edit_category or product.owner %}
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:product_update' object.pk %}"
                       role="button">Ты можешь изменить вкусняшку под себя</a>
                    {% endif %}
                </div>
            </div>
            <div class="card mb-6 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-center text-warning">Свяжитесь с нами</h4>

                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:product_create' %}"
                       role="button">Напиши свою историю вкусняшки</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Название сайта</h1>
    <p class="lead">Вредно, но вкусно</p>
</div>

<div class="container">
    <div class="row text-center">

        <div class="col-sm-12 col-lg-9 col-md-10 mx-auto">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal text-warning">Список вкусняшек</h2>
                </div>
                <div class="mb-4"></div>
                <div class="card-body">


                    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1"></a>
            <a href="?page={{ page_obj.previous_page_number }}" class="text-secondary">Предыдущая</a>
        {% endif %}
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="text-secondary">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"></a>
        {% endif %}
    </span>
                    </div>
                    {% for object in object_list %}
                    <div class="row text-align:left">
                        <div class="col-8">
                            <ol class="list-unstyled mt-3 mb-6 text-start m-3">
                                <li><h5> - {{ object|truncatechars:100 }}</h5></li>
                                {% if user.is_authenticated %}
                                {% if object.owner %}
                                <li><h6 class="text-secondary">Создатель вкусняшки: {{ object.owner }}</h6></li>
                                {% endif %}
                                {% for ver in active_versions %}
                                {% if object == ver.product %}
                                <li><h6 class="text-success-emphasis"> - {{ ver }}</h6></li>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                            </ol>
                        </div>
                        <div class="col-4">

                            <a class="btn btn-outline-warning btn-lg mb-2"
                               href="{% url 'catalog:view_product' object.pk %}"
                               role="button">Показать</a>
                            {% if user.is_authenticated %}
                            <a class="p-2 btn btn-outline-warning btn-lg mb-2"
                               href="/usercontacts/" role="button">Купить</a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-sm-10 col-lg-3 col-md-10 mx-auto">
            <div class="d-grid gap-2">

                <div class="row">
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:category' %}"
                       role="button">Список категорий</a>
                </div>
                <div class="row">
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:product_create' %}"
                       role="button">Напиши свою историю вкусняшки</a>
                </div>
                <div class="row">
                    <a class="btn btn-warning btn-lg mb-6"
                       href="{% url 'catalog:blog' %}"
                       role="button">Блог для любознательных</a>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/usercontacts_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Напиши НАМ</h2>
    <p class="lead">Здесь ты можешь отправить нам сообщение</p>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <a class="btn btn-warning btn-lg mb-6"
                   href="{% url 'catalog:my_contact' %}"
                   role="button">Здесь наши контакты</a>
            </div>
        </div>
        <div class="col-lg-2 col-md-6 col-sm-12"></div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-center">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-warning">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}